#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate ui.c with GB2312 encoded Chinese strings."""

# Define all GB2312 byte sequences for Chinese strings
CN_TITLE        = b'\xD6\xB1\xCF\xDF\xD1\xAD\xBC\xA3\xD0\xA1\xB3\xB5 v2.0'  # 直线循迹小车 v2.0
CN_SELECT_MODE  = b'\xD1\xA1\xD4\xF1\xC4\xA3\xCA\xBD'  # 选择模式
CN_TRACK_MODE   = b'\xD1\xAD\xBC\xA3\xC4\xA3\xCA\xBD'  # 循迹模式
CN_GYRO_STRAIGHT= b'\xCD\xD3\xC2\xDD\xD2\xC7\xD6\xB1\xCF\xDF'  # 陀螺仪直线
CN_BLANK1       = b'\xB4\xFD\xBF\xAA\xB7\xA2  1'  # 待开发  1
CN_BLANK2       = b'\xB4\xFD\xBF\xAA\xB7\xA2  2'  # 待开发  2
CN_BACK         = b'\xB7\xB5\xBB\xD8'  # 返回
CN_STOP         = b'\xCD\xA3\xD6\xB9'  # 停止
CN_TRACK        = b'\xD1\xAD\xBC\xA3'  # 循迹
CN_STATUS       = b'\xD7\xB4\xCC\xAC:'  # 状态:
CN_MODE         = b'\xC4\xA3\xCA\xBD:'  # 模式:
CN_ANGLE        = b'\xBD\xC7\xB6\xC8:'  # 角度:
CN_LOST         = b'\xB6\xAA\xCA\xA7:'  # 丢失:
CN_YES          = b'\xCA\xC7'  # 是
CN_NO           = b'\xB7\xF1'  # 否
CN_RUNNING      = b'\xD4\xCB\xD0\xD0\xD6\xD0'  # 运行中
CN_STOPPED      = b'\xD2\xD1\xCD\xA3\xD6\xB9'  # 已停止
CN_OUTPUT       = b'\xCA\xE4\xB3\xF6:'  # 输出:
CN_COMING_SOON  = b'\xBE\xB4\xC7\xEB\xC6\xDA\xB4\xFD...'  # 敬请期待...
CN_DEV1         = b'\xB4\xFD\xBF\xAA\xB7\xA2 1'  # 待开发 1
CN_DEV2         = b'\xB4\xFD\xBF\xAA\xB7\xA2 2'  # 待开发 2
CN_FAST         = b'\xBF\xEC'  # 快
CN_MED          = b'\xD6\xD0'  # 中
CN_SLOW         = b'\xC2\xFD'  # 慢

def b(s):
    """Wrap bytes in a C string literal."""
    return b'"' + s + b'"'

with open('USER/ui.c', 'wb') as f:
    f.write(b'#include "ui.h"\n')
    f.write(b'#include "tracking.h"\n')
    f.write(b'#include "lcd.h"\n')
    f.write(b'#include "touch.h"\n')
    f.write(b'#include "motor.h"\n')
    f.write(b'#include "debug.h"\n')
    f.write(b'\n')
    f.write(b'#define BG_COLOR       BLACK\n')
    f.write(b'#define TITLE_COLOR    CYAN\n')
    f.write(b'#define BTN_ACTIVE     GREEN\n')
    f.write(b'#define BTN_INACTIVE   DARKGRAY\n')
    f.write(b'#define BTN_TEXT       WHITE\n')
    f.write(b'#define PARAM_LABEL    LIGHTGRAY\n')
    f.write(b'#define STATUS_COLOR   YELLOW\n')
    f.write(b'\n')
    f.write(b'typedef struct { uint16_t x, y, w, h; } Rect;\n')
    f.write(b'\n')
    f.write(b'static Page_t current_page = PAGE_MAIN;\n')
    f.write(b'static uint32_t touch_tick = 0;\n')
    f.write(b'static Touch_Data_t touch;\n')
    f.write(b'\n')
    f.write(b'#define MAIN_BTN_W   300\n')
    f.write(b'#define MAIN_BTN_H   100\n')
    f.write(b'#define MAIN_BTN_GAP 40\n')
    f.write(b'static Rect main_btns[PAGE_NUM];\n')
    f.write(b'static const char *main_btn_names[] = { "", ' + b(CN_TRACK_MODE) + b', ' + b(CN_GYRO_STRAIGHT) + b', ' + b(CN_BLANK1) + b', ' + b(CN_BLANK2) + b' };\n')
    f.write(b'\n')
    f.write(b'#define BACK_BTN_X   20\n')
    f.write(b'#define BACK_BTN_Y   10\n')
    f.write(b'#define BACK_BTN_W   80\n')
    f.write(b'#define BACK_BTN_H   36\n')
    f.write(b'static Rect back_btn;\n')
    f.write(b'\n')
    f.write(b'#define TRACK_BTN_Y      60\n')
    f.write(b'#define TRACK_BTN_H      70\n')
    f.write(b'#define TRACK_BTN_W      200\n')
    f.write(b'#define TRACK_BTN_GAP    40\n')
    f.write(b'#define TRACK_PARAM_Y    180\n')
    f.write(b'#define TRACK_PARAM_ROW  60\n')
    f.write(b'#define TRACK_PARAM_BTN  50\n')
    f.write(b'#define TRACK_PARAM_BH   36\n')
    f.write(b'#define TRACK_PARAM_VW   70\n')
    f.write(b'#define TRACK_PARAM_LX   180\n')
    f.write(b'#define TRACK_STATUS_Y   395\n')
    f.write(b'#define TRACK_PARAM_NUM  3\n')
    f.write(b'\n')
    f.write(b'static Rect track_mode_btns[2];\n')
    f.write(b'static Rect track_minus[TRACK_PARAM_NUM];\n')
    f.write(b'static Rect track_plus[TRACK_PARAM_NUM];\n')
    f.write(b'static const char *track_mode_names[] = { ' + b(CN_STOP) + b', ' + b(CN_TRACK) + b' };\n')
    f.write(b'static const char *track_param_names[] = { "Base", "Slight", "Strong" };\n')
    f.write(b'static Rect track_preset_btns[3];\n')
    f.write(b'static const char *track_preset_names[] = { ' + b(CN_FAST) + b', ' + b(CN_MED) + b', ' + b(CN_SLOW) + b' };\n')
    f.write(b'/* \xBF\xEC: 350/30/60, \xD6\xD0: 250/30/70, \xC2\xFD: 180/10/50 */\n')
    f.write(b'static const int16_t track_preset_vals[3][3] = {\n')
    f.write(b'    {350, 30, 60},\n')
    f.write(b'    {250, 30, 70},\n')
    f.write(b'    {180, 10, 50}\n')
    f.write(b'};\n')
    f.write(b'\n')
    f.write(b'#define GYRO_ROW1_Y   80\n')
    f.write(b'#define GYRO_ROW2_Y   150\n')
    f.write(b'#define GYRO_ROW3_Y   230\n')
    f.write(b'#define GYRO_STATUS_Y 310\n')
    f.write(b'#define GYRO_BTN_W    50\n')
    f.write(b'#define GYRO_BTN_H    36\n')
    f.write(b'#define GYRO_VAL_W    70\n')
    f.write(b'\n')
    f.write(b'static Rect gyro_tgt_minus, gyro_tgt_plus;\n')
    f.write(b'static Rect gyro_spd_minus, gyro_spd_plus;\n')
    f.write(b'static Rect gyro_start_btn, gyro_stop_btn;\n')
    f.write(b'static int16_t gyro_speed = 200;\n')
    f.write(b'static float   gyro_target = 0.0f;\n')
    f.write(b'\n')
    f.write(b'static uint8_t PtInRect(uint16_t x, uint16_t y, Rect *r)\n{\n')
    f.write(b'    return (x >= r->x && x < r->x + r->w && y >= r->y && y < r->y + r->h) ? 1 : 0;\n}\n')
    f.write(b'\n')
    f.write(b'static void DrawBackBtn(void)\n{\n')
    f.write(b'    back_btn.x = BACK_BTN_X; back_btn.y = BACK_BTN_Y;\n')
    f.write(b'    back_btn.w = BACK_BTN_W; back_btn.h = BACK_BTN_H;\n')
    f.write(b'    LCD_DrawButtonCN(back_btn.x, back_btn.y, back_btn.w, back_btn.h,\n')
    f.write(b'                     ' + b(CN_BACK) + b', BTN_TEXT, DARKGRAY);\n}\n')
    f.write(b'\n')
    # DrawMainPage
    f.write(b'static void DrawMainPage(void)\n{\n')
    f.write(b'    uint8_t i;\n    uint16_t start_x, start_y;\n')
    f.write(b'    LCD_Clear(BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(280, 20, ' + b(CN_TITLE) + b', TITLE_COLOR, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(340, 50, ' + b(CN_SELECT_MODE) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    start_x = (800 - 2 * MAIN_BTN_W - MAIN_BTN_GAP) / 2;\n')
    f.write(b'    start_y = 100;\n')
    f.write(b'    for (i = 1; i < PAGE_NUM; i++) {\n')
    f.write(b'        uint8_t row = (i - 1) / 2;\n        uint8_t col = (i - 1) % 2;\n')
    f.write(b'        main_btns[i].x = start_x + col * (MAIN_BTN_W + MAIN_BTN_GAP);\n')
    f.write(b'        main_btns[i].y = start_y + row * (MAIN_BTN_H + MAIN_BTN_GAP);\n')
    f.write(b'        main_btns[i].w = MAIN_BTN_W;\n        main_btns[i].h = MAIN_BTN_H;\n')
    f.write(b'        LCD_DrawButtonCN(main_btns[i].x, main_btns[i].y,\n')
    f.write(b'                         main_btns[i].w, main_btns[i].h,\n')
    f.write(b'                         main_btn_names[i], BTN_TEXT, BTN_INACTIVE);\n')
    f.write(b'    }\n}\n')
    f.write(b'\n')
    # HandleMainTouch
    f.write(b'static void HandleMainTouch(uint16_t tx, uint16_t ty)\n{\n')
    f.write(b'    uint8_t i;\n')
    f.write(b'    for (i = 1; i < PAGE_NUM; i++) {\n')
    f.write(b'        if (PtInRect(tx, ty, &main_btns[i])) {\n')
    f.write(b'            Debug_Printf("Main: btn %d\\r\\n", i);\n')
    f.write(b'            UI_NavigateTo((Page_t)i);\n            return;\n')
    f.write(b'        }\n    }\n')
    f.write(b'    Debug_Printf("Main touch: x=%d y=%d\\r\\n", tx, ty);\n}\n')
    f.write(b'\n')
    # DrawTrackPage
    f.write(b'static void DrawTrackPage(void)\n{\n')
    f.write(b'    uint8_t i;\n    int16_t param_vals[3];\n')
    f.write(b'    param_vals[0] = Tracking_GetBaseSpeed();\n')
    f.write(b'    param_vals[1] = Tracking_GetSlightSpeed();\n')
    f.write(b'    param_vals[2] = Tracking_GetStrongSpeed();\n')
    f.write(b'    LCD_Clear(BG_COLOR);\n    DrawBackBtn();\n')
    f.write(b'    LCD_ShowMixedString(340, 20, ' + b(CN_TRACK_MODE) + b', TITLE_COLOR, BG_COLOR);\n')
    f.write(b'    {\n        uint16_t total_w = 2 * TRACK_BTN_W + TRACK_BTN_GAP;\n')
    f.write(b'        uint16_t sx = (800 - total_w) / 2;\n')
    f.write(b'        for (i = 0; i < 2; i++) {\n')
    f.write(b'            track_mode_btns[i].x = sx + i * (TRACK_BTN_W + TRACK_BTN_GAP);\n')
    f.write(b'            track_mode_btns[i].y = TRACK_BTN_Y;\n')
    f.write(b'            track_mode_btns[i].w = TRACK_BTN_W;\n')
    f.write(b'            track_mode_btns[i].h = TRACK_BTN_H;\n')
    f.write(b'            uint16_t c = (i == current_mode) ? BTN_ACTIVE : BTN_INACTIVE;\n')
    f.write(b'            LCD_DrawButtonCN(track_mode_btns[i].x, track_mode_btns[i].y,\n')
    f.write(b'                             track_mode_btns[i].w, track_mode_btns[i].h,\n')
    f.write(b'                             track_mode_names[i], BTN_TEXT, c);\n')
    f.write(b'        }\n    }\n')
    f.write(b'    LCD_ShowMixedString(30, 145, "PARAMS:", PARAM_LABEL, BG_COLOR);\n')
    f.write(b'    for (i = 0; i < TRACK_PARAM_NUM; i++) {\n')
    f.write(b'        uint16_t ly = TRACK_PARAM_Y + i * TRACK_PARAM_ROW;\n')
    f.write(b'        track_minus[i].x = TRACK_PARAM_LX;\n        track_minus[i].y = ly;\n')
    f.write(b'        track_minus[i].w = TRACK_PARAM_BTN;\n        track_minus[i].h = TRACK_PARAM_BH;\n')
    f.write(b'        track_plus[i].x = TRACK_PARAM_LX + TRACK_PARAM_BTN + TRACK_PARAM_VW + 15;\n')
    f.write(b'        track_plus[i].y = ly;\n        track_plus[i].w = TRACK_PARAM_BTN;\n')
    f.write(b'        track_plus[i].h = TRACK_PARAM_BH;\n')
    f.write(b'        LCD_ShowMixedString(30, ly + 10, track_param_names[i], PARAM_LABEL, BG_COLOR);\n')
    f.write(b'        LCD_DrawButtonCN(track_minus[i].x, track_minus[i].y,\n')
    f.write(b'                         track_minus[i].w, track_minus[i].h, "-", BTN_TEXT, DARKGRAY);\n')
    f.write(b'        LCD_ShowNum(track_minus[i].x + track_minus[i].w + 10, ly + 10,\n')
    f.write(b'                    param_vals[i], 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        LCD_DrawButtonCN(track_plus[i].x, track_plus[i].y,\n')
    f.write(b'                         track_plus[i].w, track_plus[i].h, "+", BTN_TEXT, DARKGRAY);\n')
    f.write(b'    }\n')
    f.write(b'    /* \xBF\xEC\xCB\xD9\xC2\xFD\xCA\xB1\xB0\xE6 */\n')
    f.write(b'    {\n')
    f.write(b'        uint16_t preset_w = 150, preset_h = 35;\n')
    f.write(b'        uint16_t preset_gap = 20;\n')
    f.write(b'        uint16_t total_preset_w = 3 * preset_w + 2 * preset_gap;\n')
    f.write(b'        uint16_t preset_sx = (800 - total_preset_w) / 2;\n')
    f.write(b'        uint16_t preset_y = 345;\n')
    f.write(b'        for (i = 0; i < 3; i++) {\n')
    f.write(b'            track_preset_btns[i].x = preset_sx + i * (preset_w + preset_gap);\n')
    f.write(b'            track_preset_btns[i].y = preset_y;\n')
    f.write(b'            track_preset_btns[i].w = preset_w;\n')
    f.write(b'            track_preset_btns[i].h = preset_h;\n')
    f.write(b'            LCD_DrawButtonCN(track_preset_btns[i].x, track_preset_btns[i].y,\n')
    f.write(b'                             track_preset_btns[i].w, track_preset_btns[i].h,\n')
    f.write(b'                             track_preset_names[i], BTN_TEXT, DARKGRAY);\n')
    f.write(b'        }\n    }\n')
    f.write(b'    LCD_ShowMixedString(30, TRACK_STATUS_Y, ' + b(CN_STATUS) + b', STATUS_COLOR, BG_COLOR);\n}\n')
    f.write(b'\n')
    # HandleTrackTouch
    f.write(b'static void HandleTrackTouch(uint16_t tx, uint16_t ty)\n{\n')
    f.write(b'    uint8_t i;\n')
    f.write(b'    for (i = 0; i < 2; i++) {\n')
    f.write(b'        if (PtInRect(tx, ty, &track_mode_btns[i])) {\n')
    f.write(b'            uint8_t j;\n            current_mode = i;\n            Motor_Stop();\n')
    f.write(b'            for (j = 0; j < 2; j++) {\n')
    f.write(b'                uint16_t c = (j == current_mode) ? BTN_ACTIVE : BTN_INACTIVE;\n')
    f.write(b'                LCD_DrawButtonCN(track_mode_btns[j].x, track_mode_btns[j].y,\n')
    f.write(b'                                 track_mode_btns[j].w, track_mode_btns[j].h,\n')
    f.write(b'                                 track_mode_names[j], BTN_TEXT, c);\n')
    f.write(b'            }\n            return;\n        }\n    }\n')
    f.write(b'    {\n')
    f.write(b'        typedef int16_t (*getter_t)(void);\n        typedef void    (*setter_t)(int16_t);\n')
    f.write(b'        getter_t getters[] = { Tracking_GetBaseSpeed, Tracking_GetSlightSpeed, Tracking_GetStrongSpeed };\n')
    f.write(b'        setter_t setters[] = { Tracking_SetBaseSpeed, Tracking_SetSlightSpeed, Tracking_SetStrongSpeed };\n')
    f.write(b'        for (i = 0; i < TRACK_PARAM_NUM; i++) {\n')
    f.write(b'            if (PtInRect(tx, ty, &track_minus[i])) {\n')
    f.write(b'                int16_t val = getters[i]() - 10;\n                if (val < 0) val = 0;\n')
    f.write(b'                setters[i](val);\n')
    f.write(b'                LCD_FillRect(track_minus[i].x + track_minus[i].w + 10,\n')
    f.write(b'                             track_minus[i].y + 10, TRACK_PARAM_VW, 16, BG_COLOR);\n')
    f.write(b'                LCD_ShowNum(track_minus[i].x + track_minus[i].w + 10,\n')
    f.write(b'                            track_minus[i].y + 10, getters[i](), 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'                return;\n            }\n')
    f.write(b'            if (PtInRect(tx, ty, &track_plus[i])) {\n')
    f.write(b'                int16_t val = getters[i]() + 10;\n                if (val > 999) val = 999;\n')
    f.write(b'                setters[i](val);\n')
    f.write(b'                LCD_FillRect(track_minus[i].x + track_minus[i].w + 10,\n')
    f.write(b'                             track_minus[i].y + 10, TRACK_PARAM_VW, 16, BG_COLOR);\n')
    f.write(b'                LCD_ShowNum(track_minus[i].x + track_minus[i].w + 10,\n')
    f.write(b'                            track_minus[i].y + 10, getters[i](), 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'                return;\n            }\n        }\n    }\n')
    f.write(b'    /* \xBF\xEC\xCB\xD9\xC2\xFD\xCA\xB1\xB0\xE6 */\n')
    f.write(b'    for (i = 0; i < 3; i++) {\n')
    f.write(b'        if (PtInRect(tx, ty, &track_preset_btns[i])) {\n')
    f.write(b'            Tracking_SetBaseSpeed(track_preset_vals[i][0]);\n')
    f.write(b'            Tracking_SetSlightSpeed(track_preset_vals[i][1]);\n')
    f.write(b'            Tracking_SetStrongSpeed(track_preset_vals[i][2]);\n')
    f.write(b'            {\n')
    f.write(b'                uint8_t j;\n')
    f.write(b'                int16_t vals[3];\n')
    f.write(b'                vals[0] = Tracking_GetBaseSpeed();\n')
    f.write(b'                vals[1] = Tracking_GetSlightSpeed();\n')
    f.write(b'                vals[2] = Tracking_GetStrongSpeed();\n')
    f.write(b'                for (j = 0; j < TRACK_PARAM_NUM; j++) {\n')
    f.write(b'                    LCD_FillRect(track_minus[j].x + track_minus[j].w + 10,\n')
    f.write(b'                                 track_minus[j].y + 10, TRACK_PARAM_VW, 16, BG_COLOR);\n')
    f.write(b'                    LCD_ShowNum(track_minus[j].x + track_minus[j].w + 10,\n')
    f.write(b'                                track_minus[j].y + 10, vals[j], 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'                }\n            }\n')
    f.write(b'            Debug_Printf("Preset %d: %d/%d/%d\\r\\n", i, track_preset_vals[i][0], track_preset_vals[i][1], track_preset_vals[i][2]);\n')
    f.write(b'            return;\n')
    f.write(b'        }\n    }\n}\n')
    f.write(b'\n')
    # UpdateTrackStatus
    f.write(b'static void UpdateTrackStatus(void)\n{\n')
    f.write(b'    float yaw = Tracking_GetYaw();\n    uint8_t lost = Tracking_GetLost();\n')
    f.write(b'    LCD_FillRect(30, TRACK_STATUS_Y + 25, 740, 80, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(30, TRACK_STATUS_Y + 25, ' + b(CN_MODE) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(80, TRACK_STATUS_Y + 25, track_mode_names[current_mode],\n')
    f.write(b'                        (current_mode == MODE_TRACK) ? GREEN : RED, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(180, TRACK_STATUS_Y + 25, ' + b(CN_ANGLE) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowNum(230, TRACK_STATUS_Y + 25, (int32_t)yaw, 6, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowMixedString(500, TRACK_STATUS_Y + 25, ' + b(CN_LOST) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(560, TRACK_STATUS_Y + 25, lost ? ' + b(CN_YES) + b' : ' + b(CN_NO) + b',\n')
    f.write(b'                        lost ? RED : GREEN, BG_COLOR);\n')
    f.write(b'    {\n        const uint16_t *raw = Tracking_GetGSRaw();\n        uint8_t ch;\n')
    f.write(b'        for (ch = 0; ch < 8; ch++) {\n')
    f.write(b'            LCD_ShowNum(350 + ch * 50, TRACK_STATUS_Y + 50, raw[ch], 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        }\n    }\n')
    f.write(b'    LCD_ShowMixedString(30, TRACK_STATUS_Y + 70, "Speed:", LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowNum(70, TRACK_STATUS_Y + 50, Tracking_GetBaseSpeed(), 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowString(120, TRACK_STATUS_Y + 50, "/", LIGHTGRAY, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowNum(135, TRACK_STATUS_Y + 50, Tracking_GetSlightSpeed(), 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowString(185, TRACK_STATUS_Y + 50, "/", LIGHTGRAY, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowNum(200, TRACK_STATUS_Y + 50, Tracking_GetStrongSpeed(), 4, WHITE, BG_COLOR, 16);\n}\n')
    f.write(b'\n')
    # DrawGyroPage
    f.write(b'static void DrawGyroPage(void)\n{\n')
    f.write(b'    LCD_Clear(BG_COLOR);\n    DrawBackBtn();\n')
    f.write(b'    LCD_ShowMixedString(320, 20, ' + b(CN_GYRO_STRAIGHT) + b', TITLE_COLOR, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(100, GYRO_ROW1_Y + 10, "Target:", PARAM_LABEL, BG_COLOR);\n')
    f.write(b'    gyro_tgt_minus.x = 260; gyro_tgt_minus.y = GYRO_ROW1_Y;\n')
    f.write(b'    gyro_tgt_minus.w = GYRO_BTN_W; gyro_tgt_minus.h = GYRO_BTN_H;\n')
    f.write(b'    gyro_tgt_plus.x  = 390; gyro_tgt_plus.y  = GYRO_ROW1_Y;\n')
    f.write(b'    gyro_tgt_plus.w  = GYRO_BTN_W; gyro_tgt_plus.h  = GYRO_BTN_H;\n')
    f.write(b'    LCD_DrawButtonCN(gyro_tgt_minus.x, gyro_tgt_minus.y, gyro_tgt_minus.w, gyro_tgt_minus.h,\n')
    f.write(b'                     "-", BTN_TEXT, DARKGRAY);\n')
    f.write(b'    LCD_ShowNum(320, GYRO_ROW1_Y + 10, (int32_t)gyro_target, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowString(370, GYRO_ROW1_Y + 10, "deg", LIGHTGRAY, BG_COLOR, 16);\n')
    f.write(b'    LCD_DrawButtonCN(gyro_tgt_plus.x, gyro_tgt_plus.y, gyro_tgt_plus.w, gyro_tgt_plus.h,\n')
    f.write(b'                     "+", BTN_TEXT, DARKGRAY);\n')
    f.write(b'    LCD_ShowMixedString(100, GYRO_ROW2_Y + 10, "Speed:", PARAM_LABEL, BG_COLOR);\n')
    f.write(b'    gyro_spd_minus.x = 260; gyro_spd_minus.y = GYRO_ROW2_Y;\n')
    f.write(b'    gyro_spd_minus.w = GYRO_BTN_W; gyro_spd_minus.h = GYRO_BTN_H;\n')
    f.write(b'    gyro_spd_plus.x  = 390; gyro_spd_plus.y  = GYRO_ROW2_Y;\n')
    f.write(b'    gyro_spd_plus.w  = GYRO_BTN_W; gyro_spd_plus.h  = GYRO_BTN_H;\n')
    f.write(b'    LCD_DrawButtonCN(gyro_spd_minus.x, gyro_spd_minus.y, gyro_spd_minus.w, gyro_spd_minus.h,\n')
    f.write(b'                     "-", BTN_TEXT, DARKGRAY);\n')
    f.write(b'    LCD_ShowNum(320, GYRO_ROW2_Y + 10, gyro_speed, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_DrawButtonCN(gyro_spd_plus.x, gyro_spd_plus.y, gyro_spd_plus.w, gyro_spd_plus.h,\n')
    f.write(b'                     "+", BTN_TEXT, DARKGRAY);\n')
    f.write(b'    gyro_start_btn.x = 220; gyro_start_btn.y = GYRO_ROW3_Y;\n')
    f.write(b'    gyro_start_btn.w = 150; gyro_start_btn.h = 50;\n')
    f.write(b'    gyro_stop_btn.x  = 430; gyro_stop_btn.y  = GYRO_ROW3_Y;\n')
    f.write(b'    gyro_stop_btn.w  = 150; gyro_stop_btn.h  = 50;\n')
    f.write(b'    LCD_DrawButtonCN(gyro_start_btn.x, gyro_start_btn.y, gyro_start_btn.w, gyro_start_btn.h,\n')
    f.write(b'                     ' + b(CN_RUNNING) + b', BTN_TEXT, GREEN);\n')
    f.write(b'    LCD_DrawButtonCN(gyro_stop_btn.x, gyro_stop_btn.y, gyro_stop_btn.w, gyro_stop_btn.h,\n')
    f.write(b'                     ' + b(CN_STOP) + b', BTN_TEXT, DARKGRAY);\n')
    f.write(b'    LCD_ShowMixedString(30, GYRO_STATUS_Y, ' + b(CN_STATUS) + b', STATUS_COLOR, BG_COLOR);\n}\n')
    f.write(b'\n')
    # HandleGyroTouch
    f.write(b'static void HandleGyroTouch(uint16_t tx, uint16_t ty)\n{\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_tgt_minus)) {\n')
    f.write(b'        gyro_target -= 5.0f;\n        if (gyro_target < -180.0f) gyro_target = -180.0f;\n')
    f.write(b'        LCD_FillRect(320, GYRO_ROW1_Y + 10, GYRO_VAL_W, 16, BG_COLOR);\n')
    f.write(b'        LCD_ShowNum(320, GYRO_ROW1_Y + 10, (int32_t)gyro_target, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        return;\n    }\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_tgt_plus)) {\n')
    f.write(b'        gyro_target += 5.0f;\n        if (gyro_target > 180.0f) gyro_target = 180.0f;\n')
    f.write(b'        LCD_FillRect(320, GYRO_ROW1_Y + 10, GYRO_VAL_W, 16, BG_COLOR);\n')
    f.write(b'        LCD_ShowNum(320, GYRO_ROW1_Y + 10, (int32_t)gyro_target, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        return;\n    }\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_spd_minus)) {\n')
    f.write(b'        gyro_speed -= 10;\n        if (gyro_speed < 0) gyro_speed = 0;\n')
    f.write(b'        LCD_FillRect(320, GYRO_ROW2_Y + 10, GYRO_VAL_W, 16, BG_COLOR);\n')
    f.write(b'        LCD_ShowNum(320, GYRO_ROW2_Y + 10, gyro_speed, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        return;\n    }\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_spd_plus)) {\n')
    f.write(b'        gyro_speed += 10;\n        if (gyro_speed > 999) gyro_speed = 999;\n')
    f.write(b'        LCD_FillRect(320, GYRO_ROW2_Y + 10, GYRO_VAL_W, 16, BG_COLOR);\n')
    f.write(b'        LCD_ShowNum(320, GYRO_ROW2_Y + 10, gyro_speed, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'        return;\n    }\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_start_btn)) {\n')
    f.write(b'        Tracking_GyroStraight_Start(gyro_target, gyro_speed);\n        return;\n    }\n')
    f.write(b'    if (PtInRect(tx, ty, &gyro_stop_btn)) {\n')
    f.write(b'        Tracking_GyroStraight_Stop();\n        return;\n    }\n')
    f.write(b'    Debug_Printf("Gyro touch: x=%d y=%d\\r\\n", tx, ty);\n}\n')
    f.write(b'\n')
    # UpdateGyroStatus
    f.write(b'static void UpdateGyroStatus(void)\n{\n')
    f.write(b'    uint8_t running = Tracking_GyroStraight_IsRunning();\n')
    f.write(b'    float yaw = Tracking_GetYaw();\n')
    f.write(b'    int16_t out = Tracking_GyroStraight_GetOutput();\n')
    f.write(b'    int32_t yaw_x10 = (int32_t)(yaw * 10);\n')
    f.write(b'    LCD_FillRect(30, GYRO_STATUS_Y + 25, 740, 60, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(30, GYRO_STATUS_Y + 25, ' + b(CN_STATUS) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(80, GYRO_STATUS_Y + 25, running ? ' + b(CN_RUNNING) + b' : ' + b(CN_STOPPED) + b',\n')
    f.write(b'                        running ? GREEN : RED, BG_COLOR);\n')
    f.write(b'    LCD_ShowMixedString(230, GYRO_STATUS_Y + 25, ' + b(CN_ANGLE) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    if (yaw_x10 < 0) {\n        LCD_ShowChar(270, GYRO_STATUS_Y + 25, \'-\', WHITE, BG_COLOR, 16);\n')
    f.write(b'        yaw_x10 = -yaw_x10;\n    }\n')
    f.write(b'    LCD_ShowNum(280, GYRO_STATUS_Y + 25, yaw_x10 / 10, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowChar(320, GYRO_STATUS_Y + 25, \'.\', WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowNum(330, GYRO_STATUS_Y + 25, yaw_x10 % 10, 1, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowString(345, GYRO_STATUS_Y + 25, "deg", LIGHTGRAY, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowMixedString(430, GYRO_STATUS_Y + 25, ' + b(CN_OUTPUT) + b', LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowNum(480, GYRO_STATUS_Y + 25, out, 5, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowMixedString(30, GYRO_STATUS_Y + 50, "Target:", LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowNum(80, GYRO_STATUS_Y + 50, (int32_t)gyro_target, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowString(130, GYRO_STATUS_Y + 50, "deg", LIGHTGRAY, BG_COLOR, 16);\n')
    f.write(b'    LCD_ShowMixedString(220, GYRO_STATUS_Y + 50, "Speed:", LIGHTGRAY, BG_COLOR);\n')
    f.write(b'    LCD_ShowNum(310, GYRO_STATUS_Y + 50, gyro_speed, 4, WHITE, BG_COLOR, 16);\n')
    f.write(b'    /* \xC6\xF4\xB6\xAF/\xCD\xA3\xD6\xB9\xB0\xB4\xC5\xA3\xC9\xFA\xCB\xB9 */\n')
    f.write(b'    LCD_DrawButtonCN(gyro_start_btn.x, gyro_start_btn.y, gyro_start_btn.w, gyro_start_btn.h,\n')
    f.write(b'                     ' + b(CN_RUNNING) + b', BTN_TEXT, running ? DARKGRAY : GREEN);\n')
    f.write(b'    LCD_DrawButtonCN(gyro_stop_btn.x, gyro_stop_btn.y, gyro_stop_btn.w, gyro_stop_btn.h,\n')
    f.write(b'                     ' + b(CN_STOP) + b', BTN_TEXT, running ? RED : DARKGRAY);\n}\n')
    f.write(b'\n')
    # Blank page
    f.write(b'static void DrawBlankPage(uint8_t idx)\n{\n')
    f.write(b'    LCD_Clear(BG_COLOR);\n    DrawBackBtn();\n')
    f.write(b'    if (idx == 3) {\n')
    f.write(b'        LCD_ShowMixedString(340, 20, ' + b(CN_DEV1) + b', TITLE_COLOR, BG_COLOR);\n')
    f.write(b'    } else {\n')
    f.write(b'        LCD_ShowMixedString(340, 20, ' + b(CN_DEV2) + b', TITLE_COLOR, BG_COLOR);\n')
    f.write(b'    }\n')
    f.write(b'    LCD_ShowMixedString(320, 220, ' + b(CN_COMING_SOON) + b', LIGHTGRAY, BG_COLOR);\n}\n')
    f.write(b'\n')
    # Public API
    f.write(b'void UI_Init(void)\n{\n    current_page = PAGE_MAIN;\n    DrawMainPage();\n}\n')
    f.write(b'\n')
    f.write(b'void UI_NavigateTo(Page_t page)\n{\n')
    f.write(b'    current_mode = MODE_STOP;\n    Motor_Stop();\n    current_page = page;\n')
    f.write(b'    switch (page) {\n')
    f.write(b'        case PAGE_MAIN:   DrawMainPage(); break;\n')
    f.write(b'        case PAGE_TRACK:  DrawTrackPage(); break;\n')
    f.write(b'        case PAGE_GYRO:   DrawGyroPage(); break;\n')
    f.write(b'        case PAGE_BLANK1: DrawBlankPage(3); break;\n')
    f.write(b'        case PAGE_BLANK2: DrawBlankPage(4); break;\n')
    f.write(b'        default: break;\n    }\n}\n')
    f.write(b'\n')
    f.write(b'Page_t UI_GetPage(void)\n{\n    return current_page;\n}\n')
    f.write(b'\n')
    f.write(b'void UI_HandleTouch(uint32_t dt_us)\n{\n')
    f.write(b'    uint16_t tx, ty;\n')
    f.write(b'    touch_tick += dt_us;\n    if (touch_tick < 50000) return;\n    touch_tick = 0;\n')
    f.write(b'    if (Touch_Scan(&touch) == 0) return;\n')
    f.write(b'    tx = touch.x[0];\n    ty = touch.y[0];\n')
    f.write(b'    if (current_page != PAGE_MAIN) {\n')
    f.write(b'        if (PtInRect(tx, ty, &back_btn)) {\n')
    f.write(b'            UI_NavigateTo(PAGE_MAIN);\n            return;\n        }\n    }\n')
    f.write(b'    switch (current_page) {\n')
    f.write(b'        case PAGE_MAIN:  HandleMainTouch(tx, ty); break;\n')
    f.write(b'        case PAGE_TRACK: HandleTrackTouch(tx, ty); break;\n')
    f.write(b'        case PAGE_GYRO:  HandleGyroTouch(tx, ty); break;\n')
    f.write(b'        default: break;\n    }\n}\n')
    f.write(b'\n')
    f.write(b'void UI_UpdateStatus(void)\n{\n')
    f.write(b'    switch (current_page) {\n')
    f.write(b'        case PAGE_TRACK: UpdateTrackStatus(); break;\n')
    f.write(b'        case PAGE_GYRO:  UpdateGyroStatus(); break;\n')
    f.write(b'        default: break;\n    }\n}\n')

# Verify
with open('USER/ui.c', 'rb') as f:
    data = f.read()
    checks = [
        (CN_TITLE, "CN_TITLE"),
        (CN_SELECT_MODE, "CN_SELECT_MODE"),
        (CN_TRACK_MODE, "CN_TRACK_MODE"),
        (CN_GYRO_STRAIGHT, "CN_GYRO_STRAIGHT"),
        (CN_BACK, "CN_BACK"),
        (CN_STOP, "CN_STOP"),
        (CN_TRACK, "CN_TRACK"),
        (CN_STATUS, "CN_STATUS"),
        (CN_RUNNING, "CN_RUNNING"),
        (CN_STOPPED, "CN_STOPPED"),
        (CN_COMING_SOON, "CN_COMING_SOON"),
    ]
    all_ok = True
    for cn, name in checks:
        if cn in data:
            print(f"  OK: {name}")
        else:
            print(f"  MISSING: {name}")
            all_ok = False
    if all_ok:
        print("\nAll Chinese strings verified OK!")
    print(f"File size: {len(data)} bytes")
